.github/workflows/code-review.yml

- Added code-review.yml github action

fix: add code review action (#5)

---

src/main/java/it/gov/pagopa/register/constants/AssetRegisterConstant.java
src/main/java/it/gov/pagopa/register/mapper/operation/ProductFileMapper.java
src/main/java/it/gov/pagopa/register/service/operation/ProductFileConsumerService.java
src/main/java/it/gov/pagopa/register/service/operation/ProductFileValidator.java
src/main/java/it/gov/pagopa/register/utils/CsvUtils.java
src/main/java/it/gov/pagopa/register/utils/Utils.java

fix: code refactor

---

src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java

fix: batch list

---

src/main/java/it/gov/pagopa/register/mapper/operation/ProductMapper.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/register/utils/EprelUtils.java
src/test/java/it/gov/pagopa/register/utils/EprelUtilsTest.java

fix: energy class sorting

---

src/main/java/it/gov/pagopa/register/mapper/operation/ProductMapper.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/register/utils/EprelUtils.java
src/test/java/it/gov/pagopa/register/utils/EprelUtilsTest.java

* energy energy sort fix
* energy sort fix
* energy sort fix
* energy sort fix

fix: premote to UAT

---

src/test/java/it/gov/pagopa/common/kafka/BaseKafkaConsumerTest.java
src/test/java/it/gov/pagopa/common/kafka/utils/BaseConsumer.java
src/test/java/it/gov/pagopa/register/service/consumer/ProductFileConsumerServiceTest.java

chore: update junit tests for BaseKafkaConsumerTest and ProductFileConsumerService

---

src/main/java/it/gov/pagopa/register/mapper/operation/ProductMapper.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/register/utils/EprelUtils.java
src/test/java/it/gov/pagopa/common/kafka/BaseKafkaConsumerTest.java
src/test/java/it/gov/pagopa/common/kafka/utils/BaseConsumer.java
src/test/java/it/gov/pagopa/register/service/consumer/ProductFileConsumerServiceTest.java
src/test/java/it/gov/pagopa/register/utils/EprelUtilsTest.java

fix: promote to UAT

---

src/main/java/it/gov/pagopa/register/constants/AssetRegisterConstants.java
src/main/java/it/gov/pagopa/register/mapper/operation/ProductFileMapper.java
src/main/java/it/gov/pagopa/register/mapper/operation/ProductMapper.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/register/service/operation/ProductFileService.java
src/main/java/it/gov/pagopa/register/service/validator/ProductFileValidatorService.java
src/main/java/it/gov/pagopa/register/utils/CsvUtils.java
src/test/java/it/gov/pagopa/register/repository/ProductFileSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductFileServiceTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductServiceTest.java
src/test/java/it/gov/pagopa/register/utils/CsvUtilsTest.java

… name and category end fix sorting by category and batch name

fix: check csv category Italian and return Italian value 

---

src/main/java/it/gov/pagopa/register/configuration/ServiceExceptionConfig.java
src/main/java/it/gov/pagopa/register/constants/RoleConstants.java
src/main/java/it/gov/pagopa/register/controller/role/consent/PortalConsentController.java
src/main/java/it/gov/pagopa/register/controller/role/consent/PortalConsentControllerImpl.java
src/main/java/it/gov/pagopa/register/exception/role/ConsentNotFoundException.java
src/main/java/it/gov/pagopa/register/service/role/PortalConsentService.java
src/main/java/it/gov/pagopa/register/service/role/PortalConsentServiceImpl.java
src/test/java/it/gov/pagopa/register/controller/role/PortalConsentControllerTest.java
src/test/java/it/gov/pagopa/register/service/role/PortalConsentServiceTest.java

fix: RDB 147 added API remove consent

---

src/main/java/it/gov/pagopa/register/controller/operation/ProductController.java
src/test/java/it/gov/pagopa/register/controller/operation/ProductControllerTest.java

fix: update status operation change

---

src/main/java/it/gov/pagopa/register/controller/operation/ProductController.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/test/java/it/gov/pagopa/register/controller/operation/ProductControllerTest.java

fix: organizationId as request param

---

src/main/java/it/gov/pagopa/register/configuration/ProductFileValidationConfig.java
src/main/java/it/gov/pagopa/register/constants/AssetRegisterConstants.java
src/main/java/it/gov/pagopa/register/dto/operation/ProductFileResult.java
src/main/java/it/gov/pagopa/register/dto/operation/ValidationResultDTO.java
src/main/java/it/gov/pagopa/register/mapper/operation/ProductMapper.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepository.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/register/service/operation/ProductFileService.java
src/main/java/it/gov/pagopa/register/service/operation/ProductService.java
src/main/java/it/gov/pagopa/register/service/validator/ProductFileValidatorService.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/register/repository/ProductSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductFileServiceTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductServiceTest.java
src/test/java/it/gov/pagopa/register/service/validator/ProductFileValidatorServiceTest.java

fix: validation file update

---

src/main/java/it/gov/pagopa/register/service/validator/ProductFileValidatorService.java

fix: read record change

---

src/main/java/it/gov/pagopa/register/controller/operation/ProductFileController.java
src/main/resources/application.yml

fix: max size update

---

.github/workflows/code-review.yml
.grype.yaml
pom.xml
src/main/java/it/gov/pagopa/register/controller/operation/ProductController.java
src/main/java/it/gov/pagopa/register/mapper/operation/ProductMapper.java
src/main/java/it/gov/pagopa/register/service/operation/ProductService.java
src/test/java/it/gov/pagopa/register/controller/operation/ProductControllerTest.java
src/test/java/it/gov/pagopa/register/mapper/ProductMapperTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductServiceTest.java

fix: Added control for status and motivation

---

src/main/java/it/gov/pagopa/register/constants/AssetRegisterConstants.java
src/main/java/it/gov/pagopa/register/controller/operation/ProductController.java
src/main/java/it/gov/pagopa/register/dto/operation/ProductDTO.java
src/main/java/it/gov/pagopa/register/mapper/operation/ProductMapper.java
src/main/java/it/gov/pagopa/register/model/operation/Product.java
src/main/java/it/gov/pagopa/register/model/operation/StatusChangeEvent.java
src/main/java/it/gov/pagopa/register/service/operation/ProductService.java
src/main/java/it/gov/pagopa/register/utils/ValidationUtils.java
src/test/java/it/gov/pagopa/register/controller/operation/ProductControllerTest.java
src/test/java/it/gov/pagopa/register/mapper/ProductMapperTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductServiceTest.java
src/test/java/it/gov/pagopa/register/service/validator/CookinghobsValidatorServiceTest.java
src/test/java/it/gov/pagopa/register/service/validator/EprelProductValidatorServiceTest.java
src/test/java/it/gov/pagopa/register/utils/ObjectMaker.java

fix: Status Change Chrono Added

---

src/main/java/it/gov/pagopa/register/constants/AssetRegisterConstants.java

fix: error message update

---

src/main/java/it/gov/pagopa/register/constants/AssetRegisterConstants.java
src/main/java/it/gov/pagopa/register/dto/utils/EprelProduct.java
src/main/java/it/gov/pagopa/register/mapper/operation/ProductMapper.java
src/test/java/it/gov/pagopa/register/mapper/ProductMapperTest.java

feat: change refrigerator's name

---

src/main/java/it/gov/pagopa/register/controller/operation/ProductController.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepository.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/register/service/operation/ProductService.java
src/test/java/it/gov/pagopa/register/controller/operation/ProductControllerTest.java
src/test/java/it/gov/pagopa/register/repository/ProductFileSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/repository/ProductSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductServiceTest.java

feat: [RDB-276] adding brand model to product filter

---

src/main/java/it/gov/pagopa/register/connector/notification/NotificationService.java
src/main/java/it/gov/pagopa/register/connector/notification/NotificationServiceImpl.java
src/main/java/it/gov/pagopa/register/controller/clean/CleanController.java
src/main/java/it/gov/pagopa/register/controller/operation/ProductController.java
src/main/java/it/gov/pagopa/register/dto/clean/CleanRequestDTO.java
src/main/java/it/gov/pagopa/register/dto/operation/ProductDTO.java
src/main/java/it/gov/pagopa/register/dto/operation/ProductUpdateStatusRequestDTO.java
src/main/java/it/gov/pagopa/register/mapper/operation/ProductMapper.java
src/main/java/it/gov/pagopa/register/model/operation/Product.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepository.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/register/service/clean/CleanService.java
src/main/java/it/gov/pagopa/register/service/operation/ProductService.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/register/connector/notification/NotificationServiceImplTest.java
src/test/java/it/gov/pagopa/register/controller/clean/CleanControllerTest.java
src/test/java/it/gov/pagopa/register/controller/operation/ProductControllerTest.java
src/test/java/it/gov/pagopa/register/repository/ProductFileSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/repository/ProductSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/service/clean/CleanServiceTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductServiceTest.java

RDB-260: formal motivation

---

src/main/java/it/gov/pagopa/register/dto/operation/ProductCriteriaDTO.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepository.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/register/service/operation/ProductService.java
src/test/java/it/gov/pagopa/register/repository/ProductFileSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/repository/ProductSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductServiceTest.java

feat: resolving sonar warning

---

src/main/java/it/gov/pagopa/register/dto/operation/ProductCriteriaDTO.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepository.java
src/main/java/it/gov/pagopa/register/repository/operation/ProductSpecificRepositoryImpl.java
src/main/java/it/gov/pagopa/register/service/operation/ProductService.java
src/test/java/it/gov/pagopa/register/repository/ProductFileSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/repository/ProductSpecificRepositoryTest.java
src/test/java/it/gov/pagopa/register/service/operation/ProductServiceTest.java

fix:RDB-269-model-and-brand-order
